//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace discoteque.ProductoSevice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice/", ConfigurationName="ProductoSevice.ProductoWS")]
    public interface ProductoWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/IngresarProductoRequest", ReplyAction="http://webservice/ProductoWS/IngresarProductoResponse")]
        discoteque.ProductoSevice.IngresarProductoResponse IngresarProducto(discoteque.ProductoSevice.IngresarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/IngresarProductoRequest", ReplyAction="http://webservice/ProductoWS/IngresarProductoResponse")]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.IngresarProductoResponse> IngresarProductoAsync(discoteque.ProductoSevice.IngresarProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/buscarProductoRequest", ReplyAction="http://webservice/ProductoWS/buscarProductoResponse")]
        discoteque.ProductoSevice.buscarProductoResponse buscarProducto(discoteque.ProductoSevice.buscarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/buscarProductoRequest", ReplyAction="http://webservice/ProductoWS/buscarProductoResponse")]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.buscarProductoResponse> buscarProductoAsync(discoteque.ProductoSevice.buscarProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/eliminarRequest", ReplyAction="http://webservice/ProductoWS/eliminarResponse")]
        discoteque.ProductoSevice.eliminarResponse eliminar(discoteque.ProductoSevice.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/eliminarRequest", ReplyAction="http://webservice/ProductoWS/eliminarResponse")]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.eliminarResponse> eliminarAsync(discoteque.ProductoSevice.eliminarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/ActualizarRequest", ReplyAction="http://webservice/ProductoWS/ActualizarResponse")]
        discoteque.ProductoSevice.ActualizarResponse Actualizar(discoteque.ProductoSevice.ActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/ActualizarRequest", ReplyAction="http://webservice/ProductoWS/ActualizarResponse")]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.ActualizarResponse> ActualizarAsync(discoteque.ProductoSevice.ActualizarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarProducto", Namespace="http://webservice/", Order=0)]
        public discoteque.ProductoSevice.IngresarProductoRequestBody Body;
        
        public IngresarProductoRequest() {
        }
        
        public IngresarProductoRequest(discoteque.ProductoSevice.IngresarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class IngresarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int stock;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int tipo;
        
        public IngresarProductoRequestBody() {
        }
        
        public IngresarProductoRequestBody(string nombre, int precio, int stock, int tipo) {
            this.nombre = nombre;
            this.precio = precio;
            this.stock = stock;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarProductoResponse", Namespace="http://webservice/", Order=0)]
        public discoteque.ProductoSevice.IngresarProductoResponseBody Body;
        
        public IngresarProductoResponse() {
        }
        
        public IngresarProductoResponse(discoteque.ProductoSevice.IngresarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class IngresarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public IngresarProductoResponseBody() {
        }
        
        public IngresarProductoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarProducto", Namespace="http://webservice/", Order=0)]
        public discoteque.ProductoSevice.buscarProductoRequestBody Body;
        
        public buscarProductoRequest() {
        }
        
        public buscarProductoRequest(discoteque.ProductoSevice.buscarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class buscarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public buscarProductoRequestBody() {
        }
        
        public buscarProductoRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarProductoResponse", Namespace="http://webservice/", Order=0)]
        public discoteque.ProductoSevice.buscarProductoResponseBody Body;
        
        public buscarProductoResponse() {
        }
        
        public buscarProductoResponse(discoteque.ProductoSevice.buscarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class buscarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public buscarProductoResponseBody() {
        }
        
        public buscarProductoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminar", Namespace="http://webservice/", Order=0)]
        public discoteque.ProductoSevice.eliminarRequestBody Body;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(discoteque.ProductoSevice.eliminarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class eliminarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public eliminarRequestBody() {
        }
        
        public eliminarRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarResponse", Namespace="http://webservice/", Order=0)]
        public discoteque.ProductoSevice.eliminarResponseBody Body;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(discoteque.ProductoSevice.eliminarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class eliminarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public eliminarResponseBody() {
        }
        
        public eliminarResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualizar", Namespace="http://webservice/", Order=0)]
        public discoteque.ProductoSevice.ActualizarRequestBody Body;
        
        public ActualizarRequest() {
        }
        
        public ActualizarRequest(discoteque.ProductoSevice.ActualizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ActualizarRequestBody {
        
        public ActualizarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarResponse", Namespace="http://webservice/", Order=0)]
        public discoteque.ProductoSevice.ActualizarResponseBody Body;
        
        public ActualizarResponse() {
        }
        
        public ActualizarResponse(discoteque.ProductoSevice.ActualizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ActualizarResponseBody() {
        }
        
        public ActualizarResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductoWSChannel : discoteque.ProductoSevice.ProductoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoWSClient : System.ServiceModel.ClientBase<discoteque.ProductoSevice.ProductoWS>, discoteque.ProductoSevice.ProductoWS {
        
        public ProductoWSClient() {
        }
        
        public ProductoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        discoteque.ProductoSevice.IngresarProductoResponse discoteque.ProductoSevice.ProductoWS.IngresarProducto(discoteque.ProductoSevice.IngresarProductoRequest request) {
            return base.Channel.IngresarProducto(request);
        }
        
        public string IngresarProducto(string nombre, int precio, int stock, int tipo) {
            discoteque.ProductoSevice.IngresarProductoRequest inValue = new discoteque.ProductoSevice.IngresarProductoRequest();
            inValue.Body = new discoteque.ProductoSevice.IngresarProductoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.precio = precio;
            inValue.Body.stock = stock;
            inValue.Body.tipo = tipo;
            discoteque.ProductoSevice.IngresarProductoResponse retVal = ((discoteque.ProductoSevice.ProductoWS)(this)).IngresarProducto(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.IngresarProductoResponse> discoteque.ProductoSevice.ProductoWS.IngresarProductoAsync(discoteque.ProductoSevice.IngresarProductoRequest request) {
            return base.Channel.IngresarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<discoteque.ProductoSevice.IngresarProductoResponse> IngresarProductoAsync(string nombre, int precio, int stock, int tipo) {
            discoteque.ProductoSevice.IngresarProductoRequest inValue = new discoteque.ProductoSevice.IngresarProductoRequest();
            inValue.Body = new discoteque.ProductoSevice.IngresarProductoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.precio = precio;
            inValue.Body.stock = stock;
            inValue.Body.tipo = tipo;
            return ((discoteque.ProductoSevice.ProductoWS)(this)).IngresarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        discoteque.ProductoSevice.buscarProductoResponse discoteque.ProductoSevice.ProductoWS.buscarProducto(discoteque.ProductoSevice.buscarProductoRequest request) {
            return base.Channel.buscarProducto(request);
        }
        
        public string buscarProducto(int id) {
            discoteque.ProductoSevice.buscarProductoRequest inValue = new discoteque.ProductoSevice.buscarProductoRequest();
            inValue.Body = new discoteque.ProductoSevice.buscarProductoRequestBody();
            inValue.Body.id = id;
            discoteque.ProductoSevice.buscarProductoResponse retVal = ((discoteque.ProductoSevice.ProductoWS)(this)).buscarProducto(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.buscarProductoResponse> discoteque.ProductoSevice.ProductoWS.buscarProductoAsync(discoteque.ProductoSevice.buscarProductoRequest request) {
            return base.Channel.buscarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<discoteque.ProductoSevice.buscarProductoResponse> buscarProductoAsync(int id) {
            discoteque.ProductoSevice.buscarProductoRequest inValue = new discoteque.ProductoSevice.buscarProductoRequest();
            inValue.Body = new discoteque.ProductoSevice.buscarProductoRequestBody();
            inValue.Body.id = id;
            return ((discoteque.ProductoSevice.ProductoWS)(this)).buscarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        discoteque.ProductoSevice.eliminarResponse discoteque.ProductoSevice.ProductoWS.eliminar(discoteque.ProductoSevice.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public string eliminar(int id) {
            discoteque.ProductoSevice.eliminarRequest inValue = new discoteque.ProductoSevice.eliminarRequest();
            inValue.Body = new discoteque.ProductoSevice.eliminarRequestBody();
            inValue.Body.id = id;
            discoteque.ProductoSevice.eliminarResponse retVal = ((discoteque.ProductoSevice.ProductoWS)(this)).eliminar(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.eliminarResponse> discoteque.ProductoSevice.ProductoWS.eliminarAsync(discoteque.ProductoSevice.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<discoteque.ProductoSevice.eliminarResponse> eliminarAsync(int id) {
            discoteque.ProductoSevice.eliminarRequest inValue = new discoteque.ProductoSevice.eliminarRequest();
            inValue.Body = new discoteque.ProductoSevice.eliminarRequestBody();
            inValue.Body.id = id;
            return ((discoteque.ProductoSevice.ProductoWS)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        discoteque.ProductoSevice.ActualizarResponse discoteque.ProductoSevice.ProductoWS.Actualizar(discoteque.ProductoSevice.ActualizarRequest request) {
            return base.Channel.Actualizar(request);
        }
        
        public string Actualizar() {
            discoteque.ProductoSevice.ActualizarRequest inValue = new discoteque.ProductoSevice.ActualizarRequest();
            inValue.Body = new discoteque.ProductoSevice.ActualizarRequestBody();
            discoteque.ProductoSevice.ActualizarResponse retVal = ((discoteque.ProductoSevice.ProductoWS)(this)).Actualizar(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.ActualizarResponse> discoteque.ProductoSevice.ProductoWS.ActualizarAsync(discoteque.ProductoSevice.ActualizarRequest request) {
            return base.Channel.ActualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<discoteque.ProductoSevice.ActualizarResponse> ActualizarAsync() {
            discoteque.ProductoSevice.ActualizarRequest inValue = new discoteque.ProductoSevice.ActualizarRequest();
            inValue.Body = new discoteque.ProductoSevice.ActualizarRequestBody();
            return ((discoteque.ProductoSevice.ProductoWS)(this)).ActualizarAsync(inValue);
        }
    }
}
