//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace discoteque.ProductoSevice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice/", ConfigurationName="ProductoSevice.ProductoWS")]
    public interface ProductoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/listarRequest", ReplyAction="http://webservice/ProductoWS/listarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        discoteque.ProductoSevice.listarResponse listar(discoteque.ProductoSevice.listarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/listarRequest", ReplyAction="http://webservice/ProductoWS/listarResponse")]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.listarResponse> listarAsync(discoteque.ProductoSevice.listarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/IngresarProductoRequest", ReplyAction="http://webservice/ProductoWS/IngresarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        discoteque.ProductoSevice.IngresarProductoResponse IngresarProducto(discoteque.ProductoSevice.IngresarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/IngresarProductoRequest", ReplyAction="http://webservice/ProductoWS/IngresarProductoResponse")]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.IngresarProductoResponse> IngresarProductoAsync(discoteque.ProductoSevice.IngresarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/buscarProductoRequest", ReplyAction="http://webservice/ProductoWS/buscarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        discoteque.ProductoSevice.buscarProductoResponse buscarProducto(discoteque.ProductoSevice.buscarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/buscarProductoRequest", ReplyAction="http://webservice/ProductoWS/buscarProductoResponse")]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.buscarProductoResponse> buscarProductoAsync(discoteque.ProductoSevice.buscarProductoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/eliminarRequest", ReplyAction="http://webservice/ProductoWS/eliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        discoteque.ProductoSevice.eliminarResponse eliminar(discoteque.ProductoSevice.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/eliminarRequest", ReplyAction="http://webservice/ProductoWS/eliminarResponse")]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.eliminarResponse> eliminarAsync(discoteque.ProductoSevice.eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/ActualizarRequest", ReplyAction="http://webservice/ProductoWS/ActualizarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        discoteque.ProductoSevice.ActualizarResponse Actualizar(discoteque.ProductoSevice.ActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/ProductoWS/ActualizarRequest", ReplyAction="http://webservice/ProductoWS/ActualizarResponse")]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.ActualizarResponse> ActualizarAsync(discoteque.ProductoSevice.ActualizarRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private comandaProducto[] comandaProductosField;
        
        private sbyte enVentaField;
        
        private int idproductoField;
        
        private bool idproductoFieldSpecified;
        
        private string nombreProductoField;
        
        private int precioField;
        
        private int stockField;
        
        private tipoproducto tipoproductoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("comandaProductos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public comandaProducto[] comandaProductos {
            get {
                return this.comandaProductosField;
            }
            set {
                this.comandaProductosField = value;
                this.RaisePropertyChanged("comandaProductos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public sbyte enVenta {
            get {
                return this.enVentaField;
            }
            set {
                this.enVentaField = value;
                this.RaisePropertyChanged("enVenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idproducto {
            get {
                return this.idproductoField;
            }
            set {
                this.idproductoField = value;
                this.RaisePropertyChanged("idproducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idproductoSpecified {
            get {
                return this.idproductoFieldSpecified;
            }
            set {
                this.idproductoFieldSpecified = value;
                this.RaisePropertyChanged("idproductoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreProducto {
            get {
                return this.nombreProductoField;
            }
            set {
                this.nombreProductoField = value;
                this.RaisePropertyChanged("nombreProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipoproducto tipoproducto {
            get {
                return this.tipoproductoField;
            }
            set {
                this.tipoproductoField = value;
                this.RaisePropertyChanged("tipoproducto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice/")]
    public partial class comandaProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private comanda comandaField;
        
        private comandaProductoId idField;
        
        private producto productoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public comanda comanda {
            get {
                return this.comandaField;
            }
            set {
                this.comandaField = value;
                this.RaisePropertyChanged("comanda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public comandaProductoId id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice/")]
    public partial class comanda : object, System.ComponentModel.INotifyPropertyChanged {
        
        private atencion atencionField;
        
        private comandaProducto[] comandaProductosField;
        
        private int idcomandaField;
        
        private bool idcomandaFieldSpecified;
        
        private int totalcomandaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public atencion atencion {
            get {
                return this.atencionField;
            }
            set {
                this.atencionField = value;
                this.RaisePropertyChanged("atencion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("comandaProductos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public comandaProducto[] comandaProductos {
            get {
                return this.comandaProductosField;
            }
            set {
                this.comandaProductosField = value;
                this.RaisePropertyChanged("comandaProductos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idcomanda {
            get {
                return this.idcomandaField;
            }
            set {
                this.idcomandaField = value;
                this.RaisePropertyChanged("idcomanda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idcomandaSpecified {
            get {
                return this.idcomandaFieldSpecified;
            }
            set {
                this.idcomandaFieldSpecified = value;
                this.RaisePropertyChanged("idcomandaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int totalcomanda {
            get {
                return this.totalcomandaField;
            }
            set {
                this.totalcomandaField = value;
                this.RaisePropertyChanged("totalcomanda");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice/")]
    public partial class atencion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private comanda[] comandasField;
        
        private sbyte faturadaField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private atencionId idField;
        
        private int propinaField;
        
        private tiposala tiposalaField;
        
        private int totalatencionField;
        
        private usuario usuarioField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("comandas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public comanda[] comandas {
            get {
                return this.comandasField;
            }
            set {
                this.comandasField = value;
                this.RaisePropertyChanged("comandas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public sbyte faturada {
            get {
                return this.faturadaField;
            }
            set {
                this.faturadaField = value;
                this.RaisePropertyChanged("faturada");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public atencionId id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int propina {
            get {
                return this.propinaField;
            }
            set {
                this.propinaField = value;
                this.RaisePropertyChanged("propina");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tiposala tiposala {
            get {
                return this.tiposalaField;
            }
            set {
                this.tiposalaField = value;
                this.RaisePropertyChanged("tiposala");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int totalatencion {
            get {
                return this.totalatencionField;
            }
            set {
                this.totalatencionField = value;
                this.RaisePropertyChanged("totalatencion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice/")]
    public partial class atencionId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idatencionField;
        
        private int usuarioIdusuarioField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idatencion {
            get {
                return this.idatencionField;
            }
            set {
                this.idatencionField = value;
                this.RaisePropertyChanged("idatencion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int usuarioIdusuario {
            get {
                return this.usuarioIdusuarioField;
            }
            set {
                this.usuarioIdusuarioField = value;
                this.RaisePropertyChanged("usuarioIdusuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice/")]
    public partial class tipoproducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionTipoPField;
        
        private int idtipoProductoField;
        
        private bool idtipoProductoFieldSpecified;
        
        private producto[] productosField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionTipoP {
            get {
                return this.descripcionTipoPField;
            }
            set {
                this.descripcionTipoPField = value;
                this.RaisePropertyChanged("descripcionTipoP");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idtipoProducto {
            get {
                return this.idtipoProductoField;
            }
            set {
                this.idtipoProductoField = value;
                this.RaisePropertyChanged("idtipoProducto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idtipoProductoSpecified {
            get {
                return this.idtipoProductoFieldSpecified;
            }
            set {
                this.idtipoProductoFieldSpecified = value;
                this.RaisePropertyChanged("idtipoProductoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("productos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public producto[] productos {
            get {
                return this.productosField;
            }
            set {
                this.productosField = value;
                this.RaisePropertyChanged("productos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice/")]
    public partial class comandaProductoId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int comandaIdcomandaField;
        
        private int productoIdproductoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int comandaIdcomanda {
            get {
                return this.comandaIdcomandaField;
            }
            set {
                this.comandaIdcomandaField = value;
                this.RaisePropertyChanged("comandaIdcomanda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int productoIdproducto {
            get {
                return this.productoIdproductoField;
            }
            set {
                this.productoIdproductoField = value;
                this.RaisePropertyChanged("productoIdproducto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice/")]
    public partial class tipousuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripciontipoUField;
        
        private int idtipoUsuarioField;
        
        private bool idtipoUsuarioFieldSpecified;
        
        private usuario[] usuariosField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripciontipoU {
            get {
                return this.descripciontipoUField;
            }
            set {
                this.descripciontipoUField = value;
                this.RaisePropertyChanged("descripciontipoU");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idtipoUsuario {
            get {
                return this.idtipoUsuarioField;
            }
            set {
                this.idtipoUsuarioField = value;
                this.RaisePropertyChanged("idtipoUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idtipoUsuarioSpecified {
            get {
                return this.idtipoUsuarioFieldSpecified;
            }
            set {
                this.idtipoUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idtipoUsuarioSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("usuarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public usuario[] usuarios {
            get {
                return this.usuariosField;
            }
            set {
                this.usuariosField = value;
                this.RaisePropertyChanged("usuarios");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private sbyte activoField;
        
        private atencion[] atencionsField;
        
        private string cuentausuarioField;
        
        private int idusuarioField;
        
        private bool idusuarioFieldSpecified;
        
        private string nombreusuarioField;
        
        private string passusuarioField;
        
        private tipousuario tipousuarioField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sbyte activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("atencions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public atencion[] atencions {
            get {
                return this.atencionsField;
            }
            set {
                this.atencionsField = value;
                this.RaisePropertyChanged("atencions");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cuentausuario {
            get {
                return this.cuentausuarioField;
            }
            set {
                this.cuentausuarioField = value;
                this.RaisePropertyChanged("cuentausuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idusuario {
            get {
                return this.idusuarioField;
            }
            set {
                this.idusuarioField = value;
                this.RaisePropertyChanged("idusuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idusuarioSpecified {
            get {
                return this.idusuarioFieldSpecified;
            }
            set {
                this.idusuarioFieldSpecified = value;
                this.RaisePropertyChanged("idusuarioSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreusuario {
            get {
                return this.nombreusuarioField;
            }
            set {
                this.nombreusuarioField = value;
                this.RaisePropertyChanged("nombreusuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string passusuario {
            get {
                return this.passusuarioField;
            }
            set {
                this.passusuarioField = value;
                this.RaisePropertyChanged("passusuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipousuario tipousuario {
            get {
                return this.tipousuarioField;
            }
            set {
                this.tipousuarioField = value;
                this.RaisePropertyChanged("tipousuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice/")]
    public partial class tiposala : object, System.ComponentModel.INotifyPropertyChanged {
        
        private atencion[] atencionsField;
        
        private string desctipoSalaField;
        
        private int idtipoSalaField;
        
        private bool idtipoSalaFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("atencions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public atencion[] atencions {
            get {
                return this.atencionsField;
            }
            set {
                this.atencionsField = value;
                this.RaisePropertyChanged("atencions");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string desctipoSala {
            get {
                return this.desctipoSalaField;
            }
            set {
                this.desctipoSalaField = value;
                this.RaisePropertyChanged("desctipoSala");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idtipoSala {
            get {
                return this.idtipoSalaField;
            }
            set {
                this.idtipoSalaField = value;
                this.RaisePropertyChanged("idtipoSala");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idtipoSalaSpecified {
            get {
                return this.idtipoSalaFieldSpecified;
            }
            set {
                this.idtipoSalaFieldSpecified = value;
                this.RaisePropertyChanged("idtipoSalaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar", WrapperNamespace="http://webservice/", IsWrapped=true)]
    public partial class listarRequest {
        
        public listarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarResponse", WrapperNamespace="http://webservice/", IsWrapped=true)]
    public partial class listarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public discoteque.ProductoSevice.producto[] @return;
        
        public listarResponse() {
        }
        
        public listarResponse(discoteque.ProductoSevice.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IngresarProducto", WrapperNamespace="http://webservice/", IsWrapped=true)]
    public partial class IngresarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int precio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int stock;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipo;
        
        public IngresarProductoRequest() {
        }
        
        public IngresarProductoRequest(string nombre, int precio, int stock, int tipo) {
            this.nombre = nombre;
            this.precio = precio;
            this.stock = stock;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IngresarProductoResponse", WrapperNamespace="http://webservice/", IsWrapped=true)]
    public partial class IngresarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public IngresarProductoResponse() {
        }
        
        public IngresarProductoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarProducto", WrapperNamespace="http://webservice/", IsWrapped=true)]
    public partial class buscarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public buscarProductoRequest() {
        }
        
        public buscarProductoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarProductoResponse", WrapperNamespace="http://webservice/", IsWrapped=true)]
    public partial class buscarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public buscarProductoResponse() {
        }
        
        public buscarProductoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://webservice/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://webservice/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Actualizar", WrapperNamespace="http://webservice/", IsWrapped=true)]
    public partial class ActualizarRequest {
        
        public ActualizarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarResponse", WrapperNamespace="http://webservice/", IsWrapped=true)]
    public partial class ActualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ActualizarResponse() {
        }
        
        public ActualizarResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductoWSChannel : discoteque.ProductoSevice.ProductoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoWSClient : System.ServiceModel.ClientBase<discoteque.ProductoSevice.ProductoWS>, discoteque.ProductoSevice.ProductoWS {
        
        public ProductoWSClient() {
        }
        
        public ProductoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        discoteque.ProductoSevice.listarResponse discoteque.ProductoSevice.ProductoWS.listar(discoteque.ProductoSevice.listarRequest request) {
            return base.Channel.listar(request);
        }
        
        public discoteque.ProductoSevice.producto[] listar() {
            discoteque.ProductoSevice.listarRequest inValue = new discoteque.ProductoSevice.listarRequest();
            discoteque.ProductoSevice.listarResponse retVal = ((discoteque.ProductoSevice.ProductoWS)(this)).listar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.listarResponse> discoteque.ProductoSevice.ProductoWS.listarAsync(discoteque.ProductoSevice.listarRequest request) {
            return base.Channel.listarAsync(request);
        }
        
        public System.Threading.Tasks.Task<discoteque.ProductoSevice.listarResponse> listarAsync() {
            discoteque.ProductoSevice.listarRequest inValue = new discoteque.ProductoSevice.listarRequest();
            return ((discoteque.ProductoSevice.ProductoWS)(this)).listarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        discoteque.ProductoSevice.IngresarProductoResponse discoteque.ProductoSevice.ProductoWS.IngresarProducto(discoteque.ProductoSevice.IngresarProductoRequest request) {
            return base.Channel.IngresarProducto(request);
        }
        
        public string IngresarProducto(string nombre, int precio, int stock, int tipo) {
            discoteque.ProductoSevice.IngresarProductoRequest inValue = new discoteque.ProductoSevice.IngresarProductoRequest();
            inValue.nombre = nombre;
            inValue.precio = precio;
            inValue.stock = stock;
            inValue.tipo = tipo;
            discoteque.ProductoSevice.IngresarProductoResponse retVal = ((discoteque.ProductoSevice.ProductoWS)(this)).IngresarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.IngresarProductoResponse> discoteque.ProductoSevice.ProductoWS.IngresarProductoAsync(discoteque.ProductoSevice.IngresarProductoRequest request) {
            return base.Channel.IngresarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<discoteque.ProductoSevice.IngresarProductoResponse> IngresarProductoAsync(string nombre, int precio, int stock, int tipo) {
            discoteque.ProductoSevice.IngresarProductoRequest inValue = new discoteque.ProductoSevice.IngresarProductoRequest();
            inValue.nombre = nombre;
            inValue.precio = precio;
            inValue.stock = stock;
            inValue.tipo = tipo;
            return ((discoteque.ProductoSevice.ProductoWS)(this)).IngresarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        discoteque.ProductoSevice.buscarProductoResponse discoteque.ProductoSevice.ProductoWS.buscarProducto(discoteque.ProductoSevice.buscarProductoRequest request) {
            return base.Channel.buscarProducto(request);
        }
        
        public string buscarProducto(int id) {
            discoteque.ProductoSevice.buscarProductoRequest inValue = new discoteque.ProductoSevice.buscarProductoRequest();
            inValue.id = id;
            discoteque.ProductoSevice.buscarProductoResponse retVal = ((discoteque.ProductoSevice.ProductoWS)(this)).buscarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.buscarProductoResponse> discoteque.ProductoSevice.ProductoWS.buscarProductoAsync(discoteque.ProductoSevice.buscarProductoRequest request) {
            return base.Channel.buscarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<discoteque.ProductoSevice.buscarProductoResponse> buscarProductoAsync(int id) {
            discoteque.ProductoSevice.buscarProductoRequest inValue = new discoteque.ProductoSevice.buscarProductoRequest();
            inValue.id = id;
            return ((discoteque.ProductoSevice.ProductoWS)(this)).buscarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        discoteque.ProductoSevice.eliminarResponse discoteque.ProductoSevice.ProductoWS.eliminar(discoteque.ProductoSevice.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public string eliminar(int id) {
            discoteque.ProductoSevice.eliminarRequest inValue = new discoteque.ProductoSevice.eliminarRequest();
            inValue.id = id;
            discoteque.ProductoSevice.eliminarResponse retVal = ((discoteque.ProductoSevice.ProductoWS)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.eliminarResponse> discoteque.ProductoSevice.ProductoWS.eliminarAsync(discoteque.ProductoSevice.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<discoteque.ProductoSevice.eliminarResponse> eliminarAsync(int id) {
            discoteque.ProductoSevice.eliminarRequest inValue = new discoteque.ProductoSevice.eliminarRequest();
            inValue.id = id;
            return ((discoteque.ProductoSevice.ProductoWS)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        discoteque.ProductoSevice.ActualizarResponse discoteque.ProductoSevice.ProductoWS.Actualizar(discoteque.ProductoSevice.ActualizarRequest request) {
            return base.Channel.Actualizar(request);
        }
        
        public string Actualizar() {
            discoteque.ProductoSevice.ActualizarRequest inValue = new discoteque.ProductoSevice.ActualizarRequest();
            discoteque.ProductoSevice.ActualizarResponse retVal = ((discoteque.ProductoSevice.ProductoWS)(this)).Actualizar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<discoteque.ProductoSevice.ActualizarResponse> discoteque.ProductoSevice.ProductoWS.ActualizarAsync(discoteque.ProductoSevice.ActualizarRequest request) {
            return base.Channel.ActualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<discoteque.ProductoSevice.ActualizarResponse> ActualizarAsync() {
            discoteque.ProductoSevice.ActualizarRequest inValue = new discoteque.ProductoSevice.ActualizarRequest();
            return ((discoteque.ProductoSevice.ProductoWS)(this)).ActualizarAsync(inValue);
        }
    }
}
