//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace discoteque.UsuarioService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice/", ConfigurationName="UsuarioService.UsuarioWS")]
    public interface UsuarioWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/UsuarioWS/LoginRequest", ReplyAction="http://webservice/UsuarioWS/LoginResponse")]
        discoteque.UsuarioService.LoginResponse Login(discoteque.UsuarioService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice/UsuarioWS/LoginRequest", ReplyAction="http://webservice/UsuarioWS/LoginResponse")]
        System.Threading.Tasks.Task<discoteque.UsuarioService.LoginResponse> LoginAsync(discoteque.UsuarioService.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://webservice/", Order=0)]
        public discoteque.UsuarioService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(discoteque.UsuarioService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string user, string password) {
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://webservice/", Order=0)]
        public discoteque.UsuarioService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(discoteque.UsuarioService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuarioWSChannel : discoteque.UsuarioService.UsuarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioWSClient : System.ServiceModel.ClientBase<discoteque.UsuarioService.UsuarioWS>, discoteque.UsuarioService.UsuarioWS {
        
        public UsuarioWSClient() {
        }
        
        public UsuarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        discoteque.UsuarioService.LoginResponse discoteque.UsuarioService.UsuarioWS.Login(discoteque.UsuarioService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string user, string password) {
            discoteque.UsuarioService.LoginRequest inValue = new discoteque.UsuarioService.LoginRequest();
            inValue.Body = new discoteque.UsuarioService.LoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            discoteque.UsuarioService.LoginResponse retVal = ((discoteque.UsuarioService.UsuarioWS)(this)).Login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<discoteque.UsuarioService.LoginResponse> discoteque.UsuarioService.UsuarioWS.LoginAsync(discoteque.UsuarioService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<discoteque.UsuarioService.LoginResponse> LoginAsync(string user, string password) {
            discoteque.UsuarioService.LoginRequest inValue = new discoteque.UsuarioService.LoginRequest();
            inValue.Body = new discoteque.UsuarioService.LoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            return ((discoteque.UsuarioService.UsuarioWS)(this)).LoginAsync(inValue);
        }
    }
}
