//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace discoteque
{
    using System;
    using System.Collections.Generic;
    
    public partial class atencion
    {
        public atencion()
        {
            this.comanda = new HashSet<comanda>();
        }
    
        public int idatencion { get; set; }
        public int totalatencion { get; set; }
        public short faturada { get; set; }
        public int propina { get; set; }
        public System.DateTime fecha { get; set; }
        public int usuario_idusuario { get; set; }
        public int tipoSala_idtipoSala { get; set; }
    
        public virtual tiposala tiposala { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<comanda> comanda { get; set; }
    }
}
