//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace discoteque
{
    using System;
    using System.Collections.Generic;
    
    public partial class comanda
    {
        public comanda()
        {
            this.comanda_producto = new HashSet<comanda_producto>();
        }
    
        public int idcomanda { get; set; }
        public int totalcomanda { get; set; }
        public int atencion_idatencion { get; set; }
        public int atencion_usuario_idusuario { get; set; }
    
        public virtual atencion atencion { get; set; }
        public virtual ICollection<comanda_producto> comanda_producto { get; set; }
    }
}
