//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace discoteque
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class discotequeEntities : DbContext
    {
        public discotequeEntities()
            : base("name=discotequeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<atencion> atencion { get; set; }
        public DbSet<comanda> comanda { get; set; }
        public DbSet<producto> producto { get; set; }
        public DbSet<tipoproducto> tipoproducto { get; set; }
        public DbSet<tiposala> tiposala { get; set; }
        public DbSet<tipousuario> tipousuario { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<comanda_producto> comanda_producto { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
