//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace discoteque
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.comanda = new HashSet<comanda>();
        }
    
        public int idproducto { get; set; }
        public string nombreProducto { get; set; }
        public int precio { get; set; }
        public int stock { get; set; }
        public short enVenta { get; set; }
        public int tipoProducto_idtipoProducto { get; set; }
    
        public virtual tipoproducto tipoproducto { get; set; }
        public virtual ICollection<comanda> comanda { get; set; }
    }
}
