//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace discoteque
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoproducto
    {
        public tipoproducto()
        {
            this.producto = new HashSet<producto>();
        }
    
        public int idtipoProducto { get; set; }
        public string descripcionTipoP { get; set; }
    
        public virtual ICollection<producto> producto { get; set; }
    }
}
